#
# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0
#

[General]
Command = craft
Branch = master
ShallowClone = True

[GeneralSettings]
Version/ConfigVersion = 6

ShortPath/Enabled = False
Compile/BuildType = Release
ContinuousIntegration/Enabled = True
Packager/Destination = ${Variables:WORKSPACE}/packages
Packager/PackageDebugSymbols = False

[BlueprintSettings]
qt-apps/mangareader.version = master

binary/mysql.ignored = True
libs/dbus.ignored = True
libs/llvm-meta.ignored = True
dev-utils/msys.ignored = True
dev-utils/perl.ignored = True
dev-utils/python2.ignored = True

[windows-cl-msvc2022-x86_64]
General/ABI = windows-cl-msvc2022-x86_64
